services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - my-app-network
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: "pY!12!hY"
      MYSQL_DB: "comm-db"
      MYSQL_HOST: localhost
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      my-app-network:
        aliases:
          - db

volumes:
  my-datavolume:

networks:
  my-app-network: